### ISSUE TITLE
コメントにテーブル内容を戻す

### ISSUE THREAD

**Issue by keichan34** [geolonia/map-render-benchmark#1]
コメントアウトされているところ

https://github.com/geolonia/map-render-benchmark/blob/240c5f63eca03b1bb7a316b7e6e057ac28925da1/src/style-render-time.js#L116-L118

をindex.jsに移して、標準出力をそのままにしてHTMLをコメント用に生成するように変更しましょう

https://github.com/geolonia/map-render-benchmark/blob/240c5f63eca03b1bb7a316b7e6e057ac28925da1/index.js#L65

**Comment by naogify** [comment]
Closed by https://github.com/geolonia/map-render-benchmark/pull/2
